"""Report generation service - PDF reports and email scheduling"""
import os
from fpdf import FPDF
from datetime import datetime, timezone, timedelta
from typing import Optional
import aiosmtplib
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email.mime.text import MIMEText
from email import encoders
import io

SMTP_HOST = os.environ.get("SMTP_HOST", "")
SMTP_PORT = int(os.environ.get("SMTP_PORT", "587"))
SMTP_USER = os.environ.get("SMTP_USER", "")
SMTP_PASSWORD = os.environ.get("SMTP_PASSWORD", "")
SMTP_FROM = os.environ.get("SMTP_FROM", "noreply@linkshield.io")
REPORTS_DIR = "/app/backend/reports"

os.makedirs(REPORTS_DIR, exist_ok=True)


def generate_scan_pdf(scan_data: dict, iocs: list, user_info: dict) -> bytes:
    """Generate a PDF report for a scan"""
    pdf = FPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    # Header
    pdf.set_font("Helvetica", "B", 20)
    pdf.cell(0, 15, "Link Shield - Scan Report", ln=True, align="C")
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(0, 8, f"Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}", ln=True, align="C")
    pdf.ln(10)

    # Scan Overview
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 10, "Scan Overview", ln=True)
    pdf.set_font("Helvetica", "", 11)
    pdf.cell(0, 7, f"Target: {scan_data.get('target', 'N/A')[:80]}", ln=True)
    pdf.cell(0, 7, f"Type: {scan_data.get('scan_type', 'N/A').upper()}", ln=True)
    pdf.cell(0, 7, f"Date: {scan_data.get('created_at', 'N/A')}", ln=True)
    pdf.cell(0, 7, f"Scanned by: {user_info.get('email', 'N/A')}", ln=True)
    pdf.ln(5)

    # Risk Assessment
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 10, "Risk Assessment", ln=True)
    risk_score = scan_data.get("risk_score", 0)
    risk_level = scan_data.get("risk_level", "unknown")
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, f"Risk Score: {risk_score}/100 ({risk_level.upper()})", ln=True)
    pdf.set_font("Helvetica", "", 11)
    detections = scan_data.get("malicious_detections", 0)
    total = scan_data.get("total_engines", 0)
    pdf.cell(0, 7, f"Detections: {detections}/{total} engines flagged as malicious", ln=True)
    pdf.ln(5)

    # Threats
    threats = scan_data.get("threats", [])
    if threats:
        pdf.set_font("Helvetica", "B", 14)
        pdf.cell(0, 10, "Detected Threats", ln=True)
        pdf.set_font("Helvetica", "", 10)
        for threat in threats[:15]:
            pdf.cell(0, 6, f"  - [{threat.get('engine', 'Unknown')}] {threat.get('result', 'N/A')[:60]}", ln=True)
        pdf.ln(5)

    # IOCs
    if iocs:
        pdf.set_font("Helvetica", "B", 14)
        pdf.cell(0, 10, f"Indicators of Compromise ({len(iocs)} found)", ln=True)
        pdf.set_font("Helvetica", "", 10)
        for ioc in iocs[:30]:
            pdf.cell(0, 6, f"  [{ioc.get('ioc_type', '?').upper()}] {ioc.get('value', 'N/A')[:70]} (conf: {ioc.get('confidence', 0)}%)", ln=True)
        pdf.ln(5)

    # Footer
    pdf.set_font("Helvetica", "I", 8)
    pdf.cell(0, 10, "This report was generated by Link Shield. For more details, visit your dashboard.", ln=True)

    return pdf.output()


def generate_summary_pdf(scans: list, user_info: dict, period: str) -> bytes:
    """Generate a summary report PDF for multiple scans"""
    pdf = FPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    pdf.set_font("Helvetica", "B", 20)
    pdf.cell(0, 15, f"Link Shield - {period.capitalize()} Report", ln=True, align="C")
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(0, 8, f"User: {user_info.get('email', 'N/A')}", ln=True, align="C")
    pdf.cell(0, 8, f"Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}", ln=True, align="C")
    pdf.ln(10)

    # Summary stats
    total = len(scans)
    critical = sum(1 for s in scans if s.get("risk_level") == "critical")
    high = sum(1 for s in scans if s.get("risk_level") == "high")
    suspicious = sum(1 for s in scans if s.get("risk_level") == "suspicious")
    safe = sum(1 for s in scans if s.get("risk_level") == "safe")

    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 10, "Summary", ln=True)
    pdf.set_font("Helvetica", "", 11)
    pdf.cell(0, 7, f"Total Scans: {total}", ln=True)
    pdf.cell(0, 7, f"Critical: {critical} | High: {high} | Suspicious: {suspicious} | Safe: {safe}", ln=True)
    pdf.ln(5)

    # Recent scans table
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 10, "Scan Details", ln=True)
    pdf.set_font("Helvetica", "", 9)
    for scan in scans[:50]:
        target = scan.get("target", "N/A")[:50]
        score = scan.get("risk_score", 0)
        level = scan.get("risk_level", "?")
        date = scan.get("created_at", "")[:10]
        pdf.cell(0, 6, f"  [{date}] {target} - Score: {score} ({level})", ln=True)

    return pdf.output()


async def send_report_email(to_email: str, subject: str, body: str, pdf_bytes: Optional[bytes] = None, filename: str = "report.pdf"):
    """Send email with optional PDF attachment"""
    if not SMTP_HOST or not SMTP_USER:
        return {"success": False, "error": "SMTP not configured"}

    msg = MIMEMultipart()
    msg["From"] = SMTP_FROM
    msg["To"] = to_email
    msg["Subject"] = subject
    msg.attach(MIMEText(body, "html"))

    if pdf_bytes:
        attachment = MIMEBase("application", "pdf")
        attachment.set_payload(pdf_bytes)
        encoders.encode_base64(attachment)
        attachment.add_header("Content-Disposition", f"attachment; filename={filename}")
        msg.attach(attachment)

    try:
        await aiosmtplib.send(
            msg,
            hostname=SMTP_HOST,
            port=SMTP_PORT,
            username=SMTP_USER,
            password=SMTP_PASSWORD,
            use_tls=True
        )
        return {"success": True}
    except Exception as e:
        return {"success": False, "error": str(e)}
